AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'test/dummy/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 140

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
    - 'lib/generators/**/*'
    - 'app/javascript/**/*'
    - 'app/controllers/**/*'
    - 'app/services/**/*'
    - 'app/models/**/*'
    - 'lib/recording_studio_attachable/configuration.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
    - 'lib/generators/**/*'
    - 'app/controllers/**/*'
    - 'app/services/**/*'

Lint/EmptyBlock:
  Exclude:
    - 'test/**/*'

Lint/NestedMethodDefinition:
  Exclude:
    - 'test/**/*'

Naming/VariableNumber:
  Exclude:
    - 'test/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
    - 'test/services/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'app/services/**/*'

Naming/PredicatePrefix:
  Exclude:
    - 'lib/recording_studio/capabilities/attachable.rb'

Style/ArgumentsForwarding:
  Enabled: false
